In this we have a dataset which contains data to evaluate a car on the basis of various parameters like no of doors,maintainance cost,buying price,its capacity these are given as its attributes
we have to declare that car is what in 4 classes and that is


unacc


acc

good


vgood





Class Values: 

unacc, acc, good, vgood 

Attributes: 

buying: vhigh, high, med, low.



maint: vhigh, high, med, low. 



doors: 2, 3, 4, 5more. 



persons: 2, 4, more. 



lug_boot: small, med, big. 


safety: low, med, high. 



In [0]:
#accessing all required libraries
import numpy as np
import pandas as pd
from sklearn import model_selection,neighbors

In [4]:
cars=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data')
print(cars.head(10))

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc
5  vhigh   vhigh  2   2    big   low  unacc
6  vhigh   vhigh  2   2    big   med  unacc
7  vhigh   vhigh  2   2    big  high  unacc
8  vhigh   vhigh  2   4  small   low  unacc
9  vhigh   vhigh  2   4  small   med  unacc


In [5]:
col_names=['Buying','Maintainance','Door','Persons','Boot_luggage','Safety','Result']
cars.columns=col_names
print(cars.head(10))

  Buying Maintainance Door Persons Boot_luggage Safety Result
0  vhigh        vhigh    2       2        small    med  unacc
1  vhigh        vhigh    2       2        small   high  unacc
2  vhigh        vhigh    2       2          med    low  unacc
3  vhigh        vhigh    2       2          med    med  unacc
4  vhigh        vhigh    2       2          med   high  unacc
5  vhigh        vhigh    2       2          big    low  unacc
6  vhigh        vhigh    2       2          big    med  unacc
7  vhigh        vhigh    2       2          big   high  unacc
8  vhigh        vhigh    2       4        small    low  unacc
9  vhigh        vhigh    2       4        small    med  unacc


In [0]:
#To Handle Non Numeric Data before fitting in classifier, we define a function to change the non numeric data into integers
def TextToNumber(df):
  columns=df.columns.values
  for column in columns:
    parseddata={}
    def ConvertToInt(value):
      return parseddata[value]
    if(df[column].dtype!=np.int64 and df[column].dtype!=np.float64):
      column_contents=df[column].values.tolist()
      unique_elements=set(column_contents)
      x=0
      for unique in unique_elements:
        if unique not in parseddata:
          parseddata[unique]=x
          x=x+1
      df[column]=list(map(ConvertToInt,df[column]))
  return df  
#Function Ends

In [7]:
y=np.array(cars['Result'])
X=np.array(TextToNumber(cars.drop(['Result'],1)))

print(X[:5])
print(y[:5])

[[3 3 2 2 1 0]
 [3 3 2 2 1 1]
 [3 3 2 2 2 2]
 [3 3 2 2 2 0]
 [3 3 2 2 2 1]]
['unacc' 'unacc' 'unacc' 'unacc' 'unacc']


In [8]:
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(X,y,test_size=0.2)
clf=neighbors.KNeighborsClassifier()

clf.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [21]:
predictdata=pd.concat([pd.Series(['vhigh']),pd.Series(['low']),pd.Series([2]),pd.Series(['more']),pd.Series(['med']),pd.Series(['low'])], axis=1)
print(predictdata)
predictdata=np.array(TextToNumber(predictdata))
print(predictdata)
predictdata.shape=(1,-1)
#print(predictdata)
prediction=clf.predict(predictdata)
print(prediction)

       0    1  2     3    4    5
0  vhigh  low  2  more  med  low
[[0 0 2 0 0 0]]
['acc']
